# A Vagrant box with the .NET SDK 2.2 on Ubuntu 18.04 LTS (Bionic Beaver)

Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/bionic64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.synced_folder "../../../repositories", "/repositories"

  config.vm.provision "shell", inline: <<-SHELL
     # Register Microsoft key and feed
     wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
     dpkg -i packages-microsoft-prod.deb
     rm -f packages-microsoft-prod.deb
     # Install the .NET SDK 2.2
     add-apt-repository universe
     apt-get install apt-transport-https -y
     apt-get update
     apt-get install dotnet-sdk-2.2 -y
  SHELL
end
