# A Vagrant box with the .NET SDK 2.2 on Ubuntu 18.04 LTS (Bionic Beaver)

Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/bionic64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.synced_folder "../../../repositories", "/repositories"

  config.vm.provision "shell", inline: <<-SHELL
     # Register Microsoft key and feed
     wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
     dpkg -i packages-microsoft-prod.deb
     rm -f packages-microsoft-prod.deb
     # Install the .NET SDK 2.2
     add-apt-repository universe
     apt-get install apt-transport-https -y
     apt-get update
     apt-get install dotnet-sdk-2.2 -y
     # Import the public key used by the package management system
     wget -qO - https://www.mongodb.org/static/pgp/server-4.0.asc | apt-key add -
     echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.0.list
     apt-get update
     apt-get install -y mongodb-org
  SHELL
end
